version: '3'

vars:
  NAME: packer-plugin-gdata
  VERSION: 1.2.0
  COMMIT: {sh: git rev-parse --verify HEAD}
  OS: linux
  ARCH: amd64
  BIN_NAME: packer-plugin-gdata_{{.VERSION}}_x5.0_{{.OS}}_{{.ARCH}}
  OUTPUT_DIR: out
  BUILD_FLAGS: -ldflags "-X main.VERSION={{.VERSION}} -X main.COMMIT={{.COMMIT}}" -o ./{{.OUTPUT_DIR}}/{{.BIN_NAME}}

tasks:
  build:
    cmds:
      - go build {{.BUILD_FLAGS}}
      - cd {{.OUTPUT_DIR}} && sha256sum {{.BIN_NAME}} > {{.BIN_NAME}}_SHA256SUM
  test:
    cmds:
      - go vet ./...
      - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.BUILD_FLAGS}} .
      - tar -czf dist/{{.NAME}}_{{.OS}}_{{.ARCH}}.tar.gz {{.NAME}}
      - rm -rf {{.NAME}}
  vendor:
    cmds:
      - dep ensure -v
  clean:
    cmds:
      - rm -rf {{.OUTPUT_DIR}} cover.out
